### ISSUE TITLE
Right channel of stereo gets lost on pipe.

### ISSUE THREAD

**Issue by tayotain** [MrKepzie/Natron#967] opened 2015-10-16 09:30 UTC
Right eye get lost on some parts of the node tree. Cannot say what causes it. On "join views" it works, but can disappear on grade node.

**Comment by MrKepzie** [comment] 2015-10-16 09:38
Can you send me a test example to reproduce the bug ?

**Comment by tayotain** [comment] 2015-10-16 09:58
heres the files.
https://www.dropbox.com/s/6l1fnzpsvcmoahv/stereo.rar?dl=0

**Comment by MrKepzie** [comment] 2015-10-17 07:59
I'm trying to debug your comp but this is not easy because they are many unused or deactivated nodes. 

First issue: you did not set in the project the number of views to 2 for stereoscopic work.

Can you send me a "stripped down" version  with minimal nodes to actually reproduce the bug ? Also a more detailed explanation of what the bug looks like or a screen cast my help me

**Comment by MrKepzie** [comment] 2015-10-17 08:52
In the meantime I have fixed a bug related to multi view a few minutes ago. You should try with a snapshot in a few hours when it is uploaded

**Comment by tayotain** [comment] 2015-10-17 18:32
A made video of the problem.

https://www.dropbox.com/s/c1y4ud7jswyydm7/Stereo_right_eye_problem.mp4?dl=0

**Comment by MrKepzie** [comment] 2015-10-17 18:39
Did you update to latest snapshot and checked if the issue was still here ?

**Comment by MrKepzie** [comment] 2015-10-26 12:38
Fixed in RC2

**Closed by MrKepzie** 2015-10-26 12:38 UTC
Labels: bug
