### ISSUE TITLE
Live read node

### ISSUE THREAD

**Issue by Ambassy** [MrKepzie/Natron#756] opened 2015-07-16 20:05 UTC
Hi!   It's vital to have a tool for live composite review. I would benefit from a live read node. Any plan on live read node?  It's necessary to look at what the comp will look like when on set. This help take perfect decisions. Eg: i'm shooting a green screen footage. At this case i need to look at how it will behave with chroma keyer node, better light adjustment.... Like: LIVE READ>CHROMA KEYER>........>VIEWER. This is extremery needed

**Comment by olear** [comment] 2015-07-17 15:17
What are the requirements? How to read the "live" stream? (where does it come from)

**Comment by devernay** [comment] 2015-07-18 11:53
We're thinking about it. The graphs will probably be limited to non-temporal effects, though (ie most keyers, mege, transforms, etc

**Comment by manuelsongokuh** [comment] 2015-07-21 20:44
hello
maybe i can to say but i'm not sure for my theory:

from firewire can use something command merge in plug? not sure.. i was used this command for live or capture , the command is dvgrab..

from HDMI this case maybe illegal because has protect HDMI-HDCP, but hdmi-hdcp is for protect for copyright this is for commercial, but can use it hdmi non-hdcp (camcorder,dsrl, etc) is legal but true problem is hardware capture/live is limited problem for legal and illegal ok?

but there is strange theory: mixer video hardware (console or decive) have same " Like: LIVE READ>CHROMA KEYER>........>VIEWER." because console has "software" for "live" but have hdmi non hdcp or RCA or VGA..

maybe needs search information for ffmpeg for capture from hdmi... but needed hardware capture/live.. ok?
my information is helpful ...?
hello

**Comment by devernay** [comment] 2015-07-22 15:08
Duplicate of #32

**Comment by devernay** [comment] 2018-04-24 07:02
This issue was moved to NatronGitHub/Natron#102

**Closed by devernay** 2018-04-24 07:02 UTC
Labels: status:duplicate, type:feature
