### ISSUE TITLE
Crash Report 5fd986b9-089a-4f7c-8c18-d5e3ff286390

### ISSUE THREAD

**Issue by troywilliams1** [MrKepzie/Natron#1473] opened 2016-10-26 19:56 UTC
**Expected behavior:** Do not crash when using Read node

**Actual behavior:** Crashed when using read node (Spawned process crashed, exiting.)

### Steps to Reproduce

1. Open Natron
2. Press tab key in node alyout, type in 'read' and hit 'enter' key
3. Press cancel when 'open Sequence dialog shows up
4. Repeat again if it doesnt immediately result in crash
5. Crash

### Versions

Natron Version 2.1.7
Copyright (C) 2016 the Natron developers
Natron version 2.1.7 at commit ef4bbc12336d62117a23442e69b4acfc4bf75c48 on branch RB-2.1 built on Oct 26 2016

OS version: Windows 8 64-bit
Dual monitor setup
Nvidia Driver version 355.82
Geforce GTX 760
Intel Core i7-3820
32GB of RAM
Resolution 1920 x 1200

**Comment by olear** [comment] 2016-10-26 21:08
Close since it's a duplicate of #1458.

**Closed by olear** 2016-10-26 21:08 UTC
