### ISSUE TITLE
Crash when save

### ISSUE THREAD

**Issue by cletort4** [MrKepzie/Natron#1071] opened 2015-12-03 11:01 UTC
Hi,
Every time I want to save project, Natron crash. Most of the time, project is saved correctly, but the software crash.

Thanks.

**Comment by MrKepzie** [comment] 2015-12-03 11:06
Which platform ?

Can you send me the project ?

**Comment by cletort4** [comment] 2015-12-03 12:33
Sure, that's an exemple of project : http://www.partage-facile.com/V0UUH7PVML/project.ntp.html
But it do that on all projects, and when I close the software too.

I work on Windows 8.1 pro 64bits. 
Processor : AMD Athlon II X4 640 3.00 GHz (a little old).
Ram : 8Go

**Comment by MrKepzie** [comment] 2015-12-04 11:29
I could not reproduce it on Win7. Can you send me a video of your screen when it crash ?

**Comment by cletort4** [comment] 2015-12-04 12:35
That's a GIF screenshot : http://img15.hostingpics.net/pics/540900captureNatron.gif
It do that for all projects. I tried Natron on linux and it works perfectly.

**Comment by cletort4** [comment] 2015-12-06 01:01
If it can help, this is my console when i just open Natron, and close Natron.

http://img11.hostingpics.net/pics/916657console.jpg

**Comment by MrKepzie** [comment] 2015-12-06 10:16
Can you try to apply the following steps:

In the start menu, in the “search”  area, type “regedit”.

The settings file of Natron is recorded in:

HKEY_CURRENT_USER\SOFTWARE\INRIA\Natron

Right click on the "Natron" folder in the regedit and click Delete and confirm.

Please retry after that

**Comment by cletort4** [comment] 2015-12-06 16:41
I do that, but always the same crash :/ I tried with the self contained zip archive too, but it's the same.

**Comment by MrKepzie** [comment] 2015-12-06 17:24
Can you try saving to another drive ?

**Comment by cletort4** [comment] 2015-12-06 17:27
Same problem :/

**Comment by cletort4** [comment] 2015-12-06 17:45
I uninstall Natron and reinstall it on an other drive too, and same problem too... I really don't understand :/

**Comment by MrKepzie** [comment] 2015-12-06 17:51
Does it happen when you open an existing project and just save (CTRL+S) (without using the file dialog)

**Comment by cletort4** [comment] 2015-12-06 18:22
Yes, it's the same problem with Ctrl+S.

**Comment by MrKepzie** [comment] 2016-01-07 14:05
Can you reproduce the bug on recent snapshots ?

**Comment by cletort4** [comment] 2016-01-07 18:06
Oh.. I don't know if I can build it :/ 

But I install Natron on an other windows, and it works. I think my computer is bad ^^

**Comment by olear** [comment] 2016-01-07 20:11
No need to build it, snapshots can be downloaded here http://downloads.natron.fr/Windows/snapshots/

I'm also unable to replicate this bug.

Could be that the partition/disk your are saving to creates the issue? Is it a regular partition, or a network disk?

**Comment by olear** [comment] 2016-01-08 19:22
Closing, please re-open if this happens again.

**Closed by olear** 2016-01-08 19:22 UTC
Labels: bug
