### ISSUE TITLE
Timeline GUI, Roto Feather Problem

### ISSUE THREAD

**Issue by TomSchl** [MrKepzie/Natron#453] opened 2015-02-09 10:24 UTC
Hi, the Timeline stays in place if the window size is ajusted (see attached image). This issue already occures immediately after starting Natron.
Furthermore the feather distance in the roto settings doesn't seem to be affected by negative values (I guess it is supposed to feather inwards).

By the way I really enjoy working with Natron.
Greetings
![natron02](https://cloud.githubusercontent.com/assets/10920573/6104411/99c6b38a-b04d-11e4-8996-c4e95cc28346.jpg)

**Comment by MrKepzie** [comment] 2015-02-09 16:24
On which platform does the problem arise ? How to reproduce it ?

There's already an issue opened about the feather distance

**Comment by TomSchl** [comment] 2015-02-09 17:27
I'm using Ubuntu 14.04 and and the issue occurs everytime the viewer window is changed in height. But the problem can be fixed temporally by a) just create a new viewer node, or b) changing the width of the property window.

**Comment by MrKepzie** [comment] 2015-02-17 21:52
This is probably a glitch due to OpenGL graphic drivers, on my ubuntu 14.04 I have no such issue

**Comment by MrKepzie** [comment] 2015-02-22 18:35
I'm going to close this. Re-open if someone else encounter the same bug

**Closed by MrKepzie** 2015-02-22 18:35 UTC
