### ISSUE TITLE
Add viewer shortcuts for fixed zoom levels

### ISSUE THREAD

**Issue by manuelsongokuh** [MrKepzie/Natron#833] opened 2015-08-11 20:49 UTC
hello

zoom of viewer is not bug, but strange nature of natron..
default is 28%, i try mouse scroll wheel until to 100% but natron does not arrive to 100% never precise...

because natron has generator from windows of viewer...(relative)

in nuke has like as "blocked" number of zoom, nuke arrives to 100% precise, not strange number..
but i respect for natron natural but NEVER to 100% under mouse scroll wheel.

for default 28% or other number for me is OK but needed 100% precise under mouse scroll wheel.. ok?

**Comment by devernay** [comment] 2015-08-11 23:26
I think there is à keystroke for 100% zoom, ans there will ne more keystroke soon for other fixes zoom levels.

**Comment by MrKepzie** [comment] 2015-08-15 04:51
duplicate of https://github.com/MrKepzie/Natron/issues/836

**Closed by MrKepzie** 2015-08-15 04:51 UTC
Labels: enhancement

**Comment by manuelsongokuh** [comment] 2015-08-31 12:10
sorry, i don’t said keystroke but i said mouse-scroll 
![link-image](http://safetyservices.ucdavis.edu/ps/ebm/copy_of_ergonomics/191pxMouse_3_Scroll.svg.png)
i use mouse-scroll it's easy and FASTER to use it..
i with natron mouse-scroll never arrive to 100% always arrive 104%, NEVER 100% ..
i did try nuke, with mouse-scroll arrive precise to 100%.. natron don’t do 100% like 'blocked'...
#836 is for keystroke (keyboard)..maybe @MrKepzie is wrong or does not understand..maybe 'est de ma faute' for my poor English..

**Comment by devernay** [comment] 2015-09-02 14:11
If you want 100% zoom exactly, why not use the keystroke? The functionality is here, why ask for more?

The mousewheel zoom is buggy in Nuke, and we have a smoother zoom in Natron.

**Comment by manuelsongokuh** [comment] 2015-09-02 17:38
@devernay : 
i used keystroke ctrl+1 for 100% is not  comfortable for me, and i did tried nuke zoom with mousewheel is very comfortable when arrived 100%.  nuke used buggy for ANY number of zoom %.
but i like natron has smoother zoom but NEVER NEVER NEVER to 100%... for this reason i said only 100% when use with mousewheel..

example:
- natron mousewheel zoom: 1,2,3,4,5,6,7,8,10,12,15, 18, 22.......95,114,135 this is smoother :+1:  but does not arrived to 100 :-1: ...why?

- nuke mousewheel zoom:1,20,50,100,120,150  this is not smoother :-1:  but it does arrived to 100 like as precise... :+1: 

***
- nuke 100 yes
- natron 100 never or il est difficile d'obtenir le nombre "100%" (comme nombre précis à 100%)

***

do you understand?

**Comment by olear** [comment] 2015-09-02 17:50
Map a mouse button to 100% ?

**Comment by manuelsongokuh** [comment] 2015-09-02 17:56
@olear 
not for map mouse button, there are variable number with mouse wheel but never to 100% but it's jump from 95% to 114%...impossible through to "100%" with mouse wheel.. so i used keyboard for enter value of zoom "100%" and [enter].. SO THIS IS NOT CONFORTABLE...
do you understand?

**Comment by olear** [comment] 2015-09-02 18:26
I understand.

my suggestion would be the option to map Viewer=>100% to a mouse button (xbutton) or something, but I tested the shortcuts editor and it don't support mouse input (as far as I can see, and test).
