### ISSUE TITLE
Natron crashes on startup - splash screen only

### ISSUE THREAD

**Issue by OldSkoolVFX** [MrKepzie/Natron#744] opened 2015-07-10 18:38 UTC
I installed the newest commit to check some bugs I posted as requested.  Indoing so Natron does not run.  I am using Ubuntu 14.04 which is up to date.  Natron is installed in my home directory with proper permissions and is executable.  The version installed is:
Natron_Linux_bundle_snapshot_x86-64bit (7/10/15)
Commit: 5468ea8784e0003836072595994022cc21237d85
On opening Natron the spash screen displays then disappears. The icon in the launcher pulses then stops.  That's it.  No Natron.  Trying to open Natron from the file manager by double clicking on the NTP file produces the same result.

**Comment by olear** [comment] 2015-07-10 18:40
Known issue on Linux, will be fixed.

**Comment by MrKepzie** [comment] 2015-07-10 18:46
It should be fixed in the next snapshot.

**Comment by MrKepzie** [comment] 2015-07-11 09:11
is this resolved ?

**Comment by olear** [comment] 2015-07-11 10:00
Works on clean install, but don't know the status for existing users.

**Comment by OldSkoolVFX** [comment] 2015-07-12 17:36
Sorry ...

The new commit:
Natron_Linux_bundle_snapshot_x86-64bit
cff3073cfee7da62f3458aca635006f4591f4127
Has the same problem on my Ubuntu 14.04.  If anything it's worse.
Thanks.

**Comment by olear** [comment] 2015-07-12 18:04
Confirmed broken again.

**Comment by OldSkoolVFX** [comment] 2015-07-12 20:47
Checked again with version below posted on 07/12/2015 at 19:56:58
Natron_Linux_bundle_snapshot_x86-64bit
Still broken with same problem.
Thanks.

**Comment by MrKepzie** [comment] 2015-07-12 20:52
It’s not gonna be fixed for another 2 days anyway I don’t have access to the build server

**Comment by olear** [comment] 2015-07-13 14:54
@OldSkoolVFX : alternative binary while you wait : http://repo.natronvfx.com/Natron-201507131552-linux-x86-release-64.tgz (note! not identical to the official binaries)

**Comment by OldSkoolVFX** [comment] 2015-07-13 18:36
On going to:
http://repo.natronvfx.com/Natron-201507131552-linux-x86-release-64.tgz
I get a '404 - Not Found' error.

**Comment by olear** [comment] 2015-07-13 18:38
Did some changes, will post new url soon.

**Comment by olear** [comment] 2015-07-13 18:46
@OldSkoolVFX : new link: http://repo.natronvfx.com/Natron-linux-x86-install-snapshot-64.tgz

**Comment by OldSkoolVFX** [comment] 2015-07-13 23:50
Thanks.  That link works.  See my comments in the associated bug reports as well.
'Roto shapes not closed on reopening file #737' - Issue is fixed.
' Problem with Mask Bleed Through During Render #740' - This issue is NOT fixed and is still present.

**Comment by MrKepzie** [comment] 2015-07-15 07:45
I cannot figure out which binary is linking to Qt 4.8.6, when I open Natron with strace or try ldd on all shared libraries they all point to 4.8.7:o

**Comment by olear** [comment] 2015-07-15 11:41
Because the Qt libs you distribute are 4.8.6(?). I copied the Qt libs from my builds (4.8.7) and your build works.

```
cd Natron
cp ../Natron2/lib/libQt* lib/
./Natron
```

**Comment by MrKepzie** [comment] 2015-07-15 14:17
> On 15 Jul 2015, at 13:41, Ole-André Rodlie <notifications@github.com> wrote:
> 



> Because the Qt libs you distribute are 4.8.6(?).
> 
hmm no, 4.8.7

Strangely I think the faulty binary is pyside because when I  type

ldd libpyside.cpython-34m.so.1.2 I get a reference to /opt/Natron/lib64/libQtCore.so.4 which is Qt 4.8.7

However when installed on another Linux platform, the same call to ldd produce a reference to /usr/lib/x86_64-linux-gnu/libQtCore.so.4 which is Qt 4.8.6 (in my case)

I can’t figure out what is linked to Qt 4.8.6

**Comment by olear** [comment] 2015-07-15 14:34
Tested libQtGui.so.4, it's indeed 4.8.7.

If you download http://repo.natronvfx.com/linux64/snapshots/fr.inria.natron.libs/2.0lib.7z and overwrite existing libQt* with libs from that your build works, so there must be something strange with your Qt libs (?).

**Comment by MrKepzie** [comment] 2015-07-15 14:34
i'll make uninstall and make install again to see if that changes anything

**Comment by MrKepzie** [comment] 2015-07-15 14:36
btw I'm having a real hard time getting glib2 to compile in order to build pango and librsvg on minnow-w64, getting tons of errors

**Comment by olear** [comment] 2015-07-15 14:38
I have 4.6.2 in /usr/lib, so if Natron was linking against that I would not get this error:
```
Cannot mix incompatible Qt library (version 0x40806) with this library (version 0x40807)
```

**Comment by olear** [comment] 2015-07-15 14:39
glib2:
Where do you build it? using a framework or manually?

**Comment by MrKepzie** [comment] 2015-07-15 14:40
manually on linux host cross compiling for win64

**Comment by olear** [comment] 2015-07-15 14:44
I need some errors or something ...

I recommend http://mxe.cc/

**Comment by MrKepzie** [comment] 2015-07-15 14:47
Switched computer to get to copy paste the errors. 
I'm using these patches from this repository https://github.com/Alexpux/MINGW-packages/tree/master/mingw-w64-glib2

When compiling basically it fails because configure is generating a wrong glib/glibconfig.h 

The culprit seems to be:

#define G_GSIZE_MODIFIER "z"
#define G_GSSIZE_MODIFIER "z"
#define G_GSIZE_FORMAT "zu"
#define G_GSSIZE_FORMAT "zi"


Mingw doesn't know "zu" however if I replace it to llu I get tons of error at different places in the code

**Comment by olear** [comment] 2015-07-15 14:57
I never tried building MSYS2 MINGW-packages, I just used the dlls from their package manager and built IM and plugin over that, cons are many dlls.

I would try MXE, I have built many qt4/qt5 shared/static apps for Win64 with that. I can do some tests.

**Comment by MrKepzie** [comment] 2015-07-15 14:58
I don't want to distribute dlls if I can avoid it, this is a pain to work with manifests and such. 
I'm looking at MXE sources of glib.mk to see how they build it...

**Comment by MrKepzie** [comment] 2015-07-17 14:51
Will be fixed when maintenance is finished on the build server

**Closed by MrKepzie** 2015-07-17 14:51 UTC
