### ISSUE TITLE
natron error - missing opengl requirements

### ISSUE THREAD

**Issue by flavitu** [MrKepzie/Natron#456] opened 2015-02-10 01:03 UTC
In my Ubuntu 14.04 I have a problem to launch the natron aplication, in my case the problem is that I have a message with (missing opengl requirements - with the natron aplication already open in background ) when I close the message all windows of Natron close.

My graphic card is old - [AMD/ATI] RV280 [Radeon 9200 PRO] (rev 01).

I have a method to pass this problem is - open terminal , then after natron command , put LIBGL_ALWAYS_SOFTWARE=1 , and run the program starts very well, but I dont have idea if all works well or work with some problems.

Thanks for this good program, and I hope that this words help users that have same problem like me.

**Comment by MrKepzie** [comment] 2015-02-10 10:47
This can be from a missing package,  try installing the following package:

libegl1-mesa

The LIBGL_ALWAYS_SOFTWARE will prevent hardware acceleration on all things using OpenGL, mainly the Viewer.

**Comment by flavitu** [comment] 2015-02-10 16:17
Thanks for reply, I already have the package libegl1-mesa, and the problem still continue on my system, so I use LIBGL_ALWAYS_SOFTWARE and works well.

Thanks for contribute .

**Comment by MrKepzie** [comment] 2015-02-11 16:02
Unfortunately I can't reproduce it, I have ubuntu 14.04 too but the problem does not arise. I don't think the graphic card, but rather the current drivers that you're using with Ubuntu. 
I'm going to close this issue here because this is not related to the source code of Natron but on your installation.

**Closed by MrKepzie** 2015-02-11 16:02 UTC
