### ISSUE TITLE
exr image planes viewer menu

### ISSUE THREAD

**Issue by gitwipo** [MrKepzie/Natron#962] opened 2015-10-14 13:35 UTC
The viewer layer drop down only shows 8 of 49 layers.
In the reader image there are all channels selectable.

**Comment by MrKepzie** [comment] 2015-10-14 14:02
Please send a sample exr file to reproduce the bug

**Comment by MrKepzie** [comment] 2015-10-14 16:38
@dgsantana  Please reply in this issue instead. Your file is reading correctly here I can see all layers in the Viewer. Can you tell me which version of Natron you are using and on which platform ?

**Comment by dgsantana** [comment] 2015-10-14 16:42
Windows 10 Pro (x64), and I tried both RC1 as well the snapshot from today.

**Comment by dgsantana** [comment] 2015-10-14 16:49
And the list of channels available (the reader detects them, but nothing seems to leave the reader, only those channels, and this happens with other multi layer exr files we have (zips scanline)).
![image](https://cloud.githubusercontent.com/assets/2750212/10490981/e84b4cc6-729b-11e5-9892-5d5218651ff0.png)

**Comment by blackearth2014** [comment] 2015-10-14 20:00
I have to agree with DGSantana. I am using Natron-201510132025-7653b56102c8b5a134d8359f95b2421e2d3663f9 version and I am still having the same issues with Blender's Multilayer EXR files.

The ReadOIIO Node.
![readeroiio-layers](https://cloud.githubusercontent.com/assets/7956901/10495893/2e7ec9e4-728c-11e5-84ea-ba29bd0bc269.png)

The ReadOIIO Node connected to a Shuffle Node.
![shuffle missing layers](https://cloud.githubusercontent.com/assets/7956901/10495894/2e81af9c-728c-11e5-99d9-812318d84271.png)

I am convinced it is not a Natron issue. I think it is a Blender multilayer file issue because some of my EXR files from blender Pre 2.75 opens with no problems and layers with ease.

**Comment by arturleao** [comment] 2015-10-14 20:05
Our file comes from 3ds Max + Vray, not blender.

**Comment by dgsantana** [comment] 2015-10-14 20:27
Tried different exr encodings and the result is the same. Also, if instead of dragging a folder to the workspace, we create a read node, anything done after the file dialog crashes Natron (selecting a file or just canceling).

**Comment by MrKepzie** [comment] 2015-10-15 12:21
@blackearth2014 Can you send me those files  not working ?

**Comment by MrKepzie** [comment] 2015-10-15 13:23
I managed to reproduce the bug on linux. Will try to fix it asap

**Comment by MrKepzie** [comment] 2015-10-15 14:01
fixed in https://github.com/MrKepzie/Natron/commit/a0c86f73b7848df44f6ec898cc3468450190842d

**Closed by MrKepzie** 2015-10-15 14:01 UTC
Labels: bug
