### ISSUE TITLE
ffmpeg broken

### ISSUE THREAD

**Issue by Montaire** [MrKepzie/Natron#478] opened 2015-02-18 21:27 UTC
On my windows ffmpeg in every working codec makes only one reference frame.
So the video quality becomes real bad after a half second. And advanced settings does not make any difference. (tested with MPEG-1,2,3,4,  H.263)
And enabling only working and supported codecs under container type would be a  huge time saver.
Also I cant get DNxHD to work.

**Comment by MrKepzie** [comment] 2015-02-18 22:06
Have you tried changing the gop (Group of Picture) size parameter ?
Do you have any output of ffmpeg in command line showing that there is only a single ref frame ?

The FFMPEG dll that we distribute is licensed under LGPL since we cannot distribute the GPL version (including x264 and more).
If you want those codec you could just download a more up to date version of FFMPEG and replace the DLLs in the plug-in IO.ofx.bundle.

**Comment by Montaire** [comment] 2015-02-18 22:32
Okay thank you!
Yes I tried 5, 12 and 15.
Also bframes on 0, 2, 5.

**Comment by paulchambers3D** [comment] 2015-02-22 00:48
On a related note. FFMPEG is very blocky. See attached screenshot. The sky in the background is a MOV file and is blocky, everything else is derived from image sequences. Any ideas?
![batesnatron_013](https://cloud.githubusercontent.com/assets/11076005/6316819/9ce9536a-ba02-11e4-8648-b04e1e6313aa.png)

**Comment by MrKepzie** [comment] 2015-02-22 08:43
What’s the configuration of your Write node ? Which format/codec are you using ?

**Comment by Montaire** [comment] 2015-02-22 09:13
On my system it looks far worse. Here is two screenshot:
![screenshot](https://cloud.githubusercontent.com/assets/9551575/6318042/1c641832-ba7b-11e4-810d-b9f5e44dd02d.PNG)
![acreenshot](https://cloud.githubusercontent.com/assets/9551575/6318044/2f1c3f0e-ba7b-11e4-9d9d-a8c544c8877d.PNG)

**Comment by paulchambers3D** [comment] 2015-02-23 15:24
Apologies, this is my first time using FFMPEG. The Bates Motel example I gave is the default node without any changes. Are there configuration aspects of FFMPEG that aren't surfaced in the Natron interface?

**Comment by MrKepzie** [comment] 2015-02-23 15:31
Please post a screenshot with the config of your WriteFFMPEG node. The format/codecs are importants, this is possible that some pairs do not work well (or not at all). There are no presets unfortunately as of now.

**Comment by paulchambers3D** [comment] 2015-02-24 12:51
Here are two screenshots. One of the node config, and another example of what the blockiness looks like...
![screen shot 2015-02-24 at 7 49 36 am](https://cloud.githubusercontent.com/assets/11076005/6349557/e5593bb2-bbf9-11e4-80c1-c1bda9db2e5a.png)

![screen shot 2015-02-24 at 7 49 43 am](https://cloud.githubusercontent.com/assets/11076005/6349562/eb9ff268-bbf9-11e4-9d3e-0117f1da3abd.png)

**Comment by MrKepzie** [comment] 2015-02-24 12:58
I’m talking about the config of your WriteFFmpeg node, the Reader node does not encode the video

**Comment by paulchambers3D** [comment] 2015-02-24 13:05
Here's the write node: 

![screen shot 2015-02-24 at 8 03 36 am](https://cloud.githubusercontent.com/assets/11076005/6349753/b3120af6-bbfb-11e4-8773-0305190bedee.png)

On further inspection in my case it looks like a desaturation I am applying to remove color may be the principle culprit. Compare the lighting seen in the original color file (Saturation 1.0) with the desaturated pass (0.0):

![screen shot 2015-02-24 at 8 02 49 am](https://cloud.githubusercontent.com/assets/11076005/6349778/e6f4a662-bbfb-11e4-86e0-9ded9affb79d.png)

![screen shot 2015-02-24 at 8 02 56 am](https://cloud.githubusercontent.com/assets/11076005/6349781/ecf37bec-bbfb-11e4-894b-57392af770d9.png)

**Comment by MrKepzie** [comment] 2015-02-24 13:08
I don’t understand, you are not telling me everything you are doing:

You export a .png sequence and then read a .mov from your Reader ?

I want to see the configuration of the Write node that exported the .mov video file

**Comment by paulchambers3D** [comment] 2015-02-24 13:10
The sky is read in from an FFMPEG reader node and is from a 24fps .MOV file. This is composited alongside several other nodes that are a combination of image sequences and other video files. Final output is a PNG sequence (although I have tried other static image formats.)

I will try an FFMPEG output to a video file and see how that looks. I haven't tried that yet.

**Comment by MrKepzie** [comment] 2015-02-24 13:13
No, you’re mistaken, what I need to know is the origin of the .mov file of the sky ? Which software exported it ? Did you do it in Natron ? If not, I can close this is issue as this has nothing to do with Natron

**Comment by paulchambers3D** [comment] 2015-02-24 13:16
Apologies. The sky was purchased from a stock house. It was not converted in Natron. Sorry if this has been a mistake on my part.

**Comment by MrKepzie** [comment] 2015-02-24 13:18
No worries. I’m afraid the issue is from the sky video that you purchased. Have you try reading it in another media player such as  VLC?  If it is blocky there too, then there is not much we can do about it

**Comment by Montaire** [comment] 2015-02-24 20:35
I just read again the feed and I overlooked "Do you have any output of ffmpeg in command line showing that there is only a single ref frame ?"
How can I enable console on windows?
And also can you reproduce the error? I can send project file, and input output video file also, if needed.

**Comment by MrKepzie** [comment] 2015-02-25 09:47
Start ---> search program , enter "cmd.exe" , there you can use ffmpeg from the command line. Go on their website for documentation on how to use it.
It would help if you send me the whole pack: project + input files so I can try to reproduce.

**Comment by Montaire** [comment] 2015-02-26 15:50
Oh I tought Natron has a console with that output, and what I couldn't find.
https://drive.google.com/file/d/0B9R0QJH-Ei5dMnQ3LVh3eDIxREU/view?usp=sharing
Here is the project, an input and an output file.

**Comment by MrKepzie** [comment] 2015-03-01 08:26
I tested for a while and was also unable to get acceptable results with mp4 format. There must be some parameters that are not tuned very well

**Comment by Montaire** [comment] 2015-03-01 16:46
What is the qscale value? It may would be nice to expose to the GUI, and an ffmpeg console string for advanced users in the writer node. Or the GUI elements could change the command line string, which would be editable.

Handbrake is a nice open source video converter with a great GUI in terms of usefulness. Trying it out or looking at the screenshots may give you some good ideas.
https://handbrake.fr/
Also it has some great dither(unbanding), and deblocking filter.
(side note: The new node side icons are awesome! They help quickly recognize nodes and also looks great in design wise.)

-----Original Message-----

**Comment by Montaire** [comment] 2015-03-01 19:32
I just realized that if the bit rate is given there is no qscale sorry.

**Comment by MrKepzie** [comment] 2015-04-08 09:27
The WriteFFMPEG node has been completly re-written so I'm closing this since its irrevelant now

**Closed by MrKepzie** 2015-04-08 09:27 UTC
Labels: bug
