### ISSUE TITLE
ShaderToy nodes render black on project reload

### ISSUE THREAD

**Issue by hpetrus** [MrKepzie/Natron#1726] opened 2018-02-08 15:58 UTC
ShaderToy nodes and PyPlugs render black when a project is reloaded into a fresh Natron session.  Dumping cache(s) and moving the time line doesn't fix the problem.

Only deleting the node and replacing it with a fresh one for that session alleviates the problem, but once you save and re-open the project, the same behaviour occurs.  You cannot remove the offending node and re-insert it into the graph to get it to work.  It must be a new one.

No errors are reported and there are no pop-ups.

OS:  Linux Mint 18.3
GPU:  2 x GTX1080 Ti
Drivers:  nVidia proprietary 390.xx

**Comment by devernay** [comment] 2018-02-18 08:38
I cannot reproduce this.
Can you please give details about the Natron version you are using, and did you test with the latest snapshot?
Does the project render correctly from the command-line ? (using NatronRenderer)
Can you post a sample project?

**Comment by fabiof17** [comment] 2018-02-26 10:17
The bug is real.
Wether you use the Windows or Linux version.

**Comment by hpetrus** [comment] 2018-02-26 10:41
The issue for community plugins is that once you save your project with a
shadertoy-using plugin, and then reload your project, the group’s input and
output nodes are disconnected. Once you go into the group and reconnect
them manually, and save, they load fine again.

**Comment by hpetrus** [comment] 2018-02-26 10:41
I smashed my head several times before I found that out. Very weird
behaviour.

**Comment by fabiof17** [comment] 2018-02-26 10:53
I had a quick look at the .ntp file. It seems to be missing the description for the Shadertoy node connections. That's why they are brocken once you reopen the project --> BUG :/

**Comment by devernay** [comment] 2018-02-26 12:29
so this happens only when the shadertoy is inside a pyplug? can you attach a sample project?

**Comment by fabiof17** [comment] 2018-02-26 15:01
[Shadertoy_PyPlug.ntp.tar.gz](https://github.com/MrKepzie/Natron/files/1759086/Shadertoy_PyPlug.ntp.tar.gz)


The PyPlug used is this one :

https://github.com/NatronVFX/natron-plugins/tree/master/GLSL/Bilateral_GL

**Comment by devernay** [comment] 2018-02-27 08:20
This may be caused caused by the fact that changedParam() is never called when loading a PyPlug:
https://github.com/MrKepzie/Natron/commit/f526b420128d23e3cca97a32ace04c44c0023b2e
https://github.com/MrKepzie/Natron/issues/1637

I'll continue the investigations

**Comment by devernay** [comment] 2018-02-27 11:02
fixed by https://github.com/NatronGitHub/Natron/commit/9ae7ce09cebd1ea8c7a0d4a42701d4d6f6665097 (but unfortunately the project has to be re-created)

**Closed by devernay** 2018-02-27 11:02 UTC
Labels: func:engine, info:feedback-needed, prio:normal, type:bug, ver:2.x
