### ISSUE TITLE
Problem loading PNG sequences

### ISSUE THREAD

**Issue by blackearth2014** [MrKepzie/Natron#1353] opened 2016-06-17 14:14 UTC
I am trying to load a greenscreen image sequence  in a PNG format from the website at http://www.hollywoodcamerawork.com/greenscreenplates.html. These PNG files work fine using the ReadOIIO decoder, but the ReadPNG decoder only reads up to 76 frames, display an error message. When I click the button to go back to the beginning and choose ReadOIIO, Natron immediately crashes.

**Comment by olear** [comment] 2016-06-17 14:32
Your crash report shows a crash in OIIO, maybe a deployment issue Mac(?). 
```
  0x3bc5f 0 libsystem_c.dylib 0x7fff94b63c5f context
  0x43169 1 libsystem_c.dylib 0x7fff94b6b169 frame_pointer 
  0x24f1 2 libgif.4.dylib 0x11d7f34f1 frame_pointer 
  0x4fb4b5 3 libOpenImageIO.1.6.dylib 0x122b8a4b5 frame_pointer 
```

**Comment by olear** [comment] 2016-06-17 14:44
I can confirm the issue on the Mac snapshot. 

Works fine on Linux using latest snapshot, note I get a warning:
```
libpng warning: Interlace handling should be turned on when using png_read_image
```

**Comment by MrKepzie** [comment] 2016-06-17 15:15
This interlace warning was fixed yesterday so I doubt this is the latest version

**Comment by blackearth2014** [comment] 2016-06-17 15:22
This is the latest snapshot that shows up on my screen - Natron-201606171341-63c69db37a33a43647b936ae80b06606603d452d.

**Comment by olear** [comment] 2016-06-17 15:24
@MrKepzie: I know, but I'm using Natron-201606171612-1c5d9292212fd2ec4a9eda51684fa10a749ae5a8-Linux-x86_64bit.tgz and openfx-io is at d69ff7e9e2a6e5192b2e6f5ee826ab4dfa6e3d6c.

**Comment by olear** [comment] 2016-06-17 15:35
The warns are only present when ReadOIIO is selected a decoder, not ReadPNG.

**Comment by MrKepzie** [comment] 2016-06-17 15:38
ah yes of course

**Comment by MrKepzie** [comment] 2016-06-17 15:42
I can reproduce the bug with the snapshot too. I guess the issue is within the libpng version, because it is not the same lib shipped for ReadPNG and ReadOIIO:

**otool -L /Applications/Natron.app/Contents/Plugins/OFX/Natron/IO.ofx.bundle/Contents/MacOS/IO.ofx 
/Applications/Natron.app/Contents/Plugins/OFX/Natron/IO.ofx.bundle/Contents/MacOS/IO.ofx:**

    @rpath/libpng16.16.dylib (compatibility version 40.0.0, current version 40.0.0)

**otool -L /Applications/Natron.app/Contents/Plugins/OFX/Natron/IO.ofx.bundle/Contents/Libraries/libOpenImageIO.1.6.dylib 
/Applications/Natron.app/Contents/Plugins/OFX/Natron/IO.ofx.bundle/Contents/Libraries/libOpenImageIO.1.6.dylib:**

    @rpath/libpng16.16.dylib (compatibility version 39.0.0, current version 39.0.0)

**Comment by devernay** [comment] 2016-06-17 15:43
This was probably upgraded (1.6.22->1.6.23) during the build

**Comment by olear** [comment] 2016-06-17 15:54
Ok, then a new snapshot should just fix this issue, I just trigger a new snapshot for Mac.

**Comment by olear** [comment] 2016-06-17 16:35
A new snapshot did not solve the issue. I guess OIIO needs to be rebuilt?

**Comment by blackearth2014** [comment] 2016-06-17 18:06
I have downloaded snapshot Natron-201606171923-e32a60461cfb46ed1652e76c44dc1a8883d61840 and the problem still exists.

![screen shot 2016-06-17 at 2 04 23 pm](https://cloud.githubusercontent.com/assets/7956901/16160171/a91c9b16-3494-11e6-9b9a-8b173b350f98.png)

**Comment by devernay** [comment] 2016-06-28 10:22
fixed by https://github.com/MrKepzie/openfx-io/commit/1749c6fc9af13cfccde7301b8ea57a82fea0afbe and https://github.com/MrKepzie/Natron/commit/922b9c6d28bd5406b6be6bf97ead59a3649054e6

**Closed by devernay** 2016-06-28 10:22 UTC
Labels: bug, readers
