### ISSUE TITLE
Latest Natron snapshots crashes when trying to insert a Write/WriteFFMpeg node.

### ISSUE THREAD

**Issue by blackearth2014** [MrKepzie/Natron#1284] opened 2016-04-08 20:53 UTC
### Problem

Natron keeps crashing when adding a WriteOIIO/WriteFFMpeg nodes to the graph from these builds
Natron-201604061854-04a54a70f3050dd81a3b1d06850512e128b04045
Natron-201604071858-04a54a70f3050dd81a3b1d06850512e128b04045

**Comment by MrKepzie** [comment] 2016-04-11 08:36
I cannot reproduce the bug

**Comment by blackearth2014** [comment] 2016-04-11 15:29
I am downloading the latest Master and RB 2.0 builds now. I will see if the problem exist in those releases.

**Comment by blackearth2014** [comment] 2016-04-11 20:07
Apparently if I save the project first, then Natron won't quit or crash. I am using the Master snapshot.

**Comment by pitiTutur** [comment] 2016-04-13 13:29
I use the same version (on Linux) and save don't solve the problem. I just can't export. =/

**Comment by olear** [comment] 2016-04-15 15:42
Should be fixed in latest RB-2.0 snapshots.

**Closed by olear** 2016-04-15 15:42 UTC
