### ISSUE TITLE
GCC 6 Build Issues (Arch Linux)

### ISSUE THREAD

**Issue by ozgursarier** [MrKepzie/Natron#1417] opened 2016-08-13 13:56 UTC
I start to make a natron PKGBUID for AUR.
Here is my PKGBUID :
http://pastebin.com/XwWUspVx
Here is config.pri :
http://pastebin.com/fRXUkWqx
Build process end with error below.
http://pastebin.com/B1usct9A

Please help me for this build error to make a package for Arch Linux users.

**Comment by olear** [comment] 2016-08-14 11:26
I will look into Arch a bit later today (need to install it on a VM).

**Comment by ozgursarier** [comment] 2016-08-14 11:31
OK, thanks.

**Comment by olear** [comment] 2016-08-14 18:46
So, had problems with GRUB after installing Arch, something seems broken. I don't want to waste any more time on that today...

I added a reference implementation for packaging Natron, it's RPM but easily adaptable for any package manager. Check out https://github.com/MrKepzie/Natron/blob/RB-2.1/Natron.spec

**Comment by ryanvade** [comment] 2016-08-15 16:22
I have run into this issue before and found that it is fixed with cleaning the build.  Try running ```make clean``` then make again.  Though I can't build either.
```/usr/include/qt4/QtGui/qtreewidget.h:45:29: fatal error: QtGui/qtreeview.h: No such file or directory```

As a side note, there is a package in the AUR that provides a static build of cairo. 
https://aur.archlinux.org/packages/cairo-static/
I suggest using that and changing the config.pri to have libcairo in /usr/local like the rest of Arch libs.

**Comment by olear** [comment] 2016-08-15 16:29
@ryanvade : Looks like a issue with Qt4 in Arch(?).

You can build without static Cairo, see the Natron.spec for more info.

**Comment by ozgursarier** [comment] 2016-08-15 16:41
cairo-static is my package. I send it to AUR to compile natron and libcairo.a is located on "/usr/lib" directory as like other distros, not in "/usr/local/lib".
It seems there is another issue. I sent my compilation error in first comment. (here: http://pastebin.com/B1usct9A )
( I am just a medical student from Turkey and this kind of errors are far beyond my understanding. )

**Comment by olear** [comment] 2016-08-15 20:03
Ok, so I installed Arch on a spare laptop. The problem is GCC 6. It now forces c++11 and that creates a couple of issues.

You can make it build by adding `QMAKE_CXXFLAGS += -std=c++98` in Gui/Gui.pro, Engine/Engine.pro and Tests/Tests.pro.

Regarding your PKGBUILD. You should aim at getting the package included in mainline instead of AUR (or does packages has to be submitted to AUR first?).

1. You should package a release, not build latest master from git
2. You should build in release mode
3. Why is Blender an opt depend?
4. You should also package openfx-arena
5. Remember to use make install
6. Use dynamic Cairo (since that is the standard in Arch (and most other distros))
7. I don't see any need to package openfx and openfx-yadif

See Natron.spec for more information.

Feel free to contact me if you have any issues packaging on Arch.

**Closed by olear** 2016-08-15 20:03 UTC

**Comment by ryanvade** [comment] 2016-08-15 23:44
I'm unable to build 2.1.2 using ```QMAKE_CXXFLAGS += -std=c++98```.

**Comment by olear** [comment] 2016-08-16 01:52
You are building against Qt5, we currently only support Qt4.

**Comment by ryanvade** [comment] 2016-08-16 17:02
What Arch packages did you install?

**Comment by olear** [comment] 2016-08-16 18:47
@ryanvade : gcc, git, make, pkgconfig, qt4, boost, expat, python2-pyside, python2-shiboken, cairo

**Comment by ozgursarier** [comment] 2016-08-16 20:53
First, I really thanks for all of your assistant.
Build ended succsessfuly by adding QMAKE_CXXFLAGS += -std=c++98 in Gui/Gui.pro, Engine/Engine.pro and Tests/Tests.pro.
----------------------
I have a little question by the way:
Do packages below must be compiled for natron in order to provide crashes, or they just opmimal dependencies?
* openfx-arena
* openfx-io
* openfx-misc
* tuttleofx
----------------------
Here is the AUR package by created with all your efforts:
https://aur.archlinux.org/packages/natron/

**Comment by olear** [comment] 2016-08-16 21:19
openfx-io, openfx-misc and openfx-arena provides the basic nodes in Natron, without them you can't do much with Natron. So you will need to package them (openfx-arena is kind of optional, but provide several read nodes that is useful(svg/psd/xcf/ora/kra etc), and also the Text node and other effects). 

Tuttle is not needed, but provide some additional nodes that may be useful (but also note that some of them don't work in Natron).

The crash reporter is only included in our official builds, since they are the only builds we support.
