### ISSUE TITLE
Read node: Setting "starting time" for image sequences results in failed render-

### ISSUE THREAD

**Issue by rebuilder** [MrKepzie/Natron#1565] opened 2017-01-27 10:49 UTC
### Problem
When an image sequence's starting time is adjusted in the Read node, write nodes downstream fail with the error "Persistent message: Failure to find requested layer in file"
### Steps to Reproduce

1. create a Read node and load an image sequence. 
2. Set the starting time of the sequence to something other than it originally was.
3. Connect a writer to the read node and use it to render out a new image sequence for a framerange that the read node should cover, given the starting time.
4. Render will fail.
5. As a workaround, leaving the starting time at default setting and retiming using a timeoffset node works.

### Versions

* **Natron version/commit** :Natron 2.2.2 version 6d43554
* **OS version:** Linux Mint 17

**Comment by MrKepzie** [comment] 2017-01-31 15:27
I cannot reproduce this bug

**Comment by PostPollux** [comment] 2017-02-01 11:50
Can't reproduce under Manjaro and Natron 2.2.3, either. Maybe post a screencast so it's easier to see all the details, like the used file formats etc.

**Comment by rebuilder** [comment] 2017-02-01 12:39
Here's a screencast. It may have something to do with project format settings, but I haven't been able to figure it out yet myself. The screencast shows me loading a dpx sequence written out from Natron. In a different project I had the same issue with an EXR sequence from Blender, but I wasn't able to reproduce it with those files in a fresh comp when I just tried.

[Kazam_screencast_00015.mp4.zip](https://github.com/MrKepzie/Natron/files/744794/Kazam_screencast_00015.mp4.zip)

**Comment by PostPollux** [comment] 2017-02-02 10:46
Mh, I still can't reproduce it. I tested it with a png sequence and a dpx sequence, but both are working well on my side.

Some questions/ideas:

- Does everything work fine when you don't change the starting time, but set the project frame range to 952-1040 instead? Just to be sure that it's related to the "starting time".

- Does the bug also occure if you save your file first? 

- 952-1040 are not 100 frames but 88. Does it work if you set your project frame range to something like 100 - 188?

**Comment by rebuilder** [comment] 2017-02-02 11:58
- Everything works fine if I don't change starting time but instead change project frame range
- The bug occurs whether or not I save the file first
-The bug occurs if I set the project frame range to match the sequence's frame range

Testing, I found that simply copying the read node with a changed starting frame to clipboard and pasting it back will result in the pasted read node erroring.

I tested with older versions of Natron I still had installed, and found that this bug does not occur in 2.1.8 but does occur in 2.1.9. I must just not have noticed it until now for.

I was able to reproduce this bug on a Windows 7 machine as well.

One important detail: I found the bug only occurs if I set the starting frame to something less than the clip's original frame. So for the example file used, if I set it to start at 953, everything is fine. If I set it to start at 951, the bug occurs.

**Comment by rebuilder** [comment] 2017-02-02 12:06
OK. Some more info. The bug occurs if the "start at" frame is outside the original framerange of the clip.
So for the example clip, with a framerange of 952-1040, the bug occurs if the starting frame is set to 951 or less, or 1041 or more.

**Comment by PostPollux** [comment] 2017-02-02 12:18
Still can't reproduce, no matter if I set the "starting time" below or above the orignial frame range of the loaded clip... really strange.
Do you have the same problem with other sequences? For example some png sequences?

**Comment by rebuilder** [comment] 2017-02-02 12:47
I've had it with every sequence I've tried so far. I've attached a demo project with an image sequence. This actually appears to work when I load the project up, but when scrubbing the frames, at some points it will spit out the "failure to find requested layer" error. If I try to copy the read node with ctrl-c and paste it back in, however, it bugs out every time. Can you test with this project on your end?


[readbug_demo.zip](https://github.com/MrKepzie/Natron/files/747717/readbug_demo.zip)

**Comment by PostPollux** [comment] 2017-02-02 14:06
When I open that file the read node has indeed an error. It says: "Read1 error: Failure to find requested layer in file"

This is really strange. I can reproduce it with your image sequence, but not with one of mine.

Also, I noticed, that it breaks, as soon as I save the file. So when I create a new natron file, import your sequence and change the starting time to 80, there is no error in the read file. Now when I save it and open it again, the error is there. When I cange it to 100 again, the error is still there. Then I save it, open it again and the error is gone. So I guess it has something to do with what's going on in the saving process...

**Comment by rebuilder** [comment] 2017-02-02 14:33
That's consistent with what I get. I'm not sure it's to do with saving, though - simply copying and pasting the read node in a fresh comp that's never been saved will also cause this bug to surface.

Interesting that you get it with these images but not others. I believe all sequences I've tried have come from the same Linux PC. I'll look into this a bit.

**Comment by PostPollux** [comment] 2017-02-02 16:18
I tested it with two different sequences, one on my server and another on my local c drive under windows. Both worked. Here is my sequence that works perfectly fine here. I'm doing exactly the same as described above with changing "starting time" it to 80 instead of 100 and then save it, then reopen it, and it still works... I'm curios if it causes problems on your side...
https://mab.to/spVFd1MPD

**Comment by rebuilder** [comment] 2017-02-02 21:09
Your files work for me. On further testing, this time on yet another computer, it seems jpg, exr, and dpx sequences yield this bug, but png does not. Can you confirm?

**Comment by PostPollux** [comment] 2017-02-02 23:05
YES, I can confirm this. I converted a dpx sequenc into jpg, png, and exr. I dragged all 4 sequences into one natron project. For each reader I changed the "starting time" to exact the same value (outside of the original framerange of the sequence). I saved the script and loaded it again and voila: 
Only the png sequence works. The other three readers show the "Failure to find requested layer in file" error!

![reader_bug](https://cloud.githubusercontent.com/assets/9008901/22572433/6990257e-e9a4-11e6-97f3-5b832ec8320a.jpeg)

**Comment by jdent02** [comment] 2017-05-12 21:23
FYI I have also stumbled on this error using JPG sequences.

**Comment by devernay** [comment] 2018-03-28 14:08
Is this fixed? I fixed several bugs regarding starting time

**Comment by PostPollux** [comment] 2018-03-28 19:31
I will test it tomorrow!

**Comment by PostPollux** [comment] 2018-03-28 19:31
I will test it tomorrow!

**Comment by PostPollux** [comment] 2018-03-29 12:08
Works fine now in 2.3.9! Can't reproduce it anymore. You can close this issue, now. Thanks!

**Comment by devernay** [comment] 2018-03-31 08:58
thanks @PostPollux

**Closed** 2018-03-31 08:58 UTC
Labels: func:readers, prio:high, type:bug, ver:2.x
