### ISSUE TITLE
Clone nodes bugs

### ISSUE THREAD

**Issue by Montaire** [MrKepzie/Natron#410] opened 2015-01-20 13:00 UTC
Deleting source node makes Natron freeze
R0625 Pure Virtual Function Call when extracting source node (only every 4-5. attempt)
I am not sure if it is a bug or limitation but LUT, roto (nodes with not just sliders) can not be cloned.

**Comment by MrKepzie** [comment] 2015-01-20 13:02
This is a bug and will be fixed in next version

**Comment by MrKepzie** [comment] 2015-01-21 14:26
In fact this is not a bug, rather this is something not implemented: Parametric curves (such as ColorLookup) and Bezier curves (such as in Roto) are not cloned.
This should be implemented for v2

**Comment by MrKepzie** [comment] 2015-02-01 16:13
Okay I implemented the clone of parametric curves (like the LUT), but did not implement the cloning of Roto shapes as I don't see why one would clone entirely a Roto node instead of just using the same node.

**Closed** 2015-02-01 16:13 UTC
Labels: bug

**Comment by Montaire** [comment] 2015-02-01 17:24
Awsome!
