### ISSUE TITLE
NatronRenderer 2.0 throwing an error 

### ISSUE THREAD

**Issue by cg-cnu** [MrKepzie/Natron#983] opened 2015-10-27 06:38 UTC
When launching command line renders we are getting this error message..
~~~
Restoring the image cache...
Restoring user settings...
init.py script not loaded
init.py script not loaded
Loading PyPlugs...
Traceback (most recent call last):
  File "<string>", line 2, in <module>
  File "/opt/Natron2/Plugins/PySide/__init__.py", line 41, in <module>
    _setupQtDirectories()
  File "/opt/Natron2/Plugins/PySide/__init__.py", line 9, in _setupQtDirectories
    from . import _utils
ValueError: Attempted relative import in non-package
Rendering started
Frame rendered: 7169 (100.0%)
Time elapsed for frame: 34.80 sec(s)
Time remaining: 0 sec(s)
Rendering finished
~~~
Thought not stopping/crashing the renders, its better we get it fixed.
Cheers.

**Comment by MrKepzie** [comment] 2015-10-27 15:15
Seems not to be critical and Linux Only

**Comment by olear** [comment] 2015-10-27 17:21
Happens in regular 'Natron' as well (see project error log), I didn't catch this one before release since I only tested 'Natron' not 'NatronRenderer'. But this does not seems to affect anything, it just setup (already existing) qt paths?

quickfix: Uncomment last line in Plugins/PySide/__init__.py to get rid of the error/warn.

**Comment by cg-cnu** [comment] 2015-10-28 05:44
@MrKepzie Yes, not a work stopping issue. 
@olear Thanks, commented for now.

**Comment by MrKepzie** [comment] 2015-10-28 07:33
What I do not understand is why it is not recognised as a package.

**Comment by ramellij** [comment] 2015-11-09 11:35
Same issue trying to render on a Windows renderfarm using Afanasy : it renders only the first task group and can't jump to the next (https://github.com/CGRU/cgru/issues/158)

**Comment by MrKepzie** [comment] 2015-11-09 11:38
This is probably unrelated. This Python error is just a warning. 
On the other hand, if the render fails somehow, this is probably unrelated and you should try to reproduce the issue with the GUI version (of Natron)

**Comment by olear** [comment] 2015-12-18 21:41
Fixed in latest snapshot.

**Closed by olear** 2015-12-18 21:41 UTC
Labels: bug
