### ISSUE TITLE
layer issue

### ISSUE THREAD

**Issue by mathiastesar** [MrKepzie/Natron#1029] opened 2015-11-18 23:31 UTC
Hi team, 
I have an issue while adding additional layers to my comp.
I m trying to output a multi layer exr, most of the shuffle copies are working fine in the viewer but i have this weird displaying issue for some others (the files in each inputs have the same file parameters, exr half float).
Thanks ! :^)
![exr_layer](https://cloud.githubusercontent.com/assets/15384202/11257806/46634aa6-8e22-11e5-8f11-187466a040cd.png)

**Comment by MrKepzie** [comment] 2015-11-19 08:27
I cannot reproduce the issue. Does it fail when linking just the viewer to the Reader with the faulty image ? If so, can you send me the image.

**Comment by mathiastesar** [comment] 2015-11-19 19:35
Nope, i have no issues when viewing the images separately. 
I had an other weird issue when it crashed. When i reopened the file with autosave the group inputs switched randomely. (my pcam read node was connected to the sta_albedo input of the group instead of viz_pcam as an example ).
Surprisingly the pcam showed properly in the sta_albedo layer in the viewer. 
It was one of the read not showing properly before.
The shuffle nodes of my group are all properly setup, i double checked.

**Comment by MrKepzie** [comment] 2015-11-20 08:37
Probably fixed in RC4

**Comment by olear** [comment] 2015-12-09 16:12
Was it fixed in RC4/RC5?

**Comment by mathiastesar** [comment] 2015-12-11 16:55
Hi team, the issue is not fixed on RC5

**Comment by MrKepzie** [comment] 2015-12-11 16:58
Mathias, send me privately the project + sample images to reproduce the bug, this must come from the Reader

**Comment by MrKepzie** [comment] 2015-12-26 09:47
Was fixed in https://github.com/MrKepzie/openfx-io/commit/21daca209fd580ff1991b09eb6303e6bbe311b81

Re-open if this is not fixed

**Closed by MrKepzie** 2015-12-26 09:47 UTC
Labels: bug
