### ISSUE TITLE
Read multiple files at once

### ISSUE THREAD

**Issue by danezmotion** [MrKepzie/Natron#1788] opened 2021-06-06 06:32 UTC
### Problem

Hello, I was trying to read multiple files at once. But, when I hit " r " in my keyboard and the file browser comes up, I’m only able to select one file at a time. I've asked on the forums for ways to do this. But, it seems the only way to achieve this, is by drag and drop. The problem with this solution is that some of us don't use a desktop environment and drag and drop is very limited. So, I wanted to ask if this can be implemented withing the file browser in a future release.

Ive also found this python script that seems to do it. But, I have no idea how implement it to work within Natron. 

http://www.nukepedia.com/python/import/export/multiread

Hopefully you find this useful

**Expected behavior:** [What you expected to happen]
Hit " r " on keyboard and when the file manager window opens, drag-select all files within a folder and hit enter/accept.
All read nodes should be created with the imported material the same way it happens with only one. 

https://www.youtube.com/watch?v=P2uXI_qPrYY 
minute 9:55 

**Actual behavior:** [What actually happened]
while in the read file browser window you can only select one file.

### Versions

* **Natron version/commit**  Natron 2.4.0
* **OS version:**  - Arch linux

Thank you

**Comment by devernay** [comment] 2021-06-07 02:09
Duplicate of https://github.com/NatronGitHub/Natron/issues/165 (which is transferred from https://github.com/MrKepzie/Natron/issues/1423).
Please continue the discussion on https://github.com/NatronGitHub/Natron/issues/165, or on https://discuss.pixls.us/c/software/natron

**Closed as completed by devernay** 2021-06-07 02:09 UTC
