### ISSUE TITLE
Viewer does not refresh if reader contains a path with non-latin characters

### ISSUE THREAD

**Issue by devernay** [MrKepzie/Natron#1416] opened 2016-08-10 14:34 UTC
The issue was notified on the FB group by user 楊景貴

He made a video: https://youtu.be/zoGX_y0lCrY

This looks like a windows unicode path problem again. The viewer does not refresh when the user scrubs the timeline, but the image is correctly rendered when the user changes the "first frame" parameter in the reader.

I don't have windows, so I can't check. @olear can you give it a try?

copy-paste a few chinese chars in a directory name, the image names being `####.png`

### Versions

* **Natron version/commit** (they can be retrieved from the About Window): 2.1.2
* **OS version:** windows vista, 7 or 8 (guessed from the video)

**Comment by olear** [comment] 2016-08-10 15:05
Confirmed in 2.0.5 and 2.1.2 on Windows 7.

**Comment by devernay** [comment] 2016-08-11 14:59
thanks

**Comment by MrKepzie** [comment] 2016-09-19 12:44
Seems to be fixed for 2.1.4, re-open if it occurs again.

**Comment by devernay** [comment] 2016-09-21 08:09
@olear can you please test again?

**Comment by olear** [comment] 2016-09-21 08:16
Confirmed fixed in 2.1.4.

**Closed by olear** 2016-09-21 08:16 UTC
Labels: bug, engine, ready, viewer
