### ISSUE TITLE
B alpha unchecks in Merge with RGB is fed into it

### ISSUE THREAD

**Issue by ElDirector** [MrKepzie/Natron#1704] opened 2017-12-11 18:47 UTC
### Problem

When merging RGBA over RGB, the alpha input of the B input becomes unchecked, causing alpha issues in the viewer and final renders.  

**Expected behavior:** I would expect Natron to create a blank alpha upon reading in the footage, as this is what happens in Nuke, preventing the issue from occurring.  
**Actual behavior:** What does happen is that footage is read in without an empty A channel which leads to the issue above.  

Adding a shuffle immediately after the read node creates an A channel and eliminates the issue.  It's just one more step though to go through when compositing CG on live action backgrounds.

### Steps to Reproduce

1. read in background footage that's RGB
2. read in a foreground image that's RGBA
3. merge the foreground over the background
4. The A input of the background becomes unchecked creating undesirable behavior.  

### Versions

This happens on all versions I've used, including the latest 2.3.3 and on all operating systems.

**Comment by ElDirector** [comment] 2017-12-11 18:54
[Merge Issue.ntp.zip](https://github.com/MrKepzie/Natron/files/1549004/Merge.Issue.ntp.zip)

**Comment by devernay** [comment] 2017-12-11 19:58
see https://www.facebook.com/groups/NatronNation/permalink/907321616102074/

**Comment by ElDirector** [comment] 2017-12-11 20:44
![screen shot 2017-12-11 at 12 40 33](https://user-images.githubusercontent.com/22898215/33852915-05d18218-de71-11e7-8e80-4ac7a7f2293c.png)
![screen shot 2017-12-11 at 12 40 13](https://user-images.githubusercontent.com/22898215/33852916-05ea21a6-de71-11e7-9549-9fe3e23af7ea.png)

These two images better show the results of the way things currently work.

**Comment by devernay** [comment] 2017-12-11 21:59
duplicate of https://github.com/MrKepzie/Natron/issues/1482

**Comment by devernay** [comment] 2017-12-11 22:06
I actually get the same result (second image) with Nuke.
If I check "auto alpha" in the reader, I get the first image, which is the same as setting "Output Components" in the reader to "RGBA" in Natron (no need to add a shuffle).
So I don't see how the default behavior is different from Nuke.

**Comment by devernay** [comment] 2017-12-11 22:10
Unless you added some extra magic in your Nuke's menu.py, as explained there: http://community.foundry.com/discuss/topic/99331

**Comment by ElDirector** [comment] 2017-12-11 22:23
Interesting.  I haven't modified Nuke hardly at all, I don't check auto alpha in Nuke and still get the top image.  I can see that the reader in Nuke is created with an alpha built in, even if auto alpha is off. 
![screen shot 2017-12-11 at 10 36 52](https://user-images.githubusercontent.com/22898215/33856807-2f6f0bce-de7e-11e7-90ce-bca01be3f12e.png)

Well, at least I know what's actually happening and how to work around it.  You're right, selecting the output to RGBA does solve the issue.  Is it easy as a non-techy user to configure it to be automatic?

**Comment by ElDirector** [comment] 2017-12-11 22:31
Come to think of it, I have had read nodes in Nuke come in as RGB and do funky stuff with merges.  The fix someone told me was to add a transform node after the read and it would create the A channel.  Thanks for helping to clear things up.

**Closed** 2017-12-11 22:31 UTC
