### ISSUE TITLE
Windows: crash in file dialog

### ISSUE THREAD

**Issue by bebinalpha** [MrKepzie/Natron#1458] opened 2016-09-30 10:36 UTC
Natron version 2.1.4 Release.
Natron crashes everytime i try to load a image or image sequence with read node. This happens randomly.
i use windows. I tried to do the same in multiple systems but every time the crash happens randomly. is there any workaround for it

**Comment by olear** [comment] 2016-09-30 10:46
We have several crash reports regarding this issue on Windows, but currently we are not able to replicate this issue on Windows 7/10.

Could you provide more information that would help us debug this issue? Windows version, hardware specs, file types (a link to a file would be great), and how you added the files to Natron (a screencast would be great).

**Comment by MrKepzie** [comment] 2016-09-30 12:13
This is a crash in the file dialog on Windows. We have multiple reports but are unable on our side  to reproduce the bug. This has to be with a configuration of Windows

**Comment by troywilliams1** [comment] 2016-10-01 21:27
Give this a quick try... I am able to reproduce this 100 percent on my machine.

1. Open Natron
2. Press Tab key in node layout , type in 'read' and hit 'enter' key
3. Press cancel when 'open sequence' dialogue shows up
4. Crash

Notes: I am seeing the crash happen much more frequently from 'tab' searching for nodes instead of right clicking and seeking the node through the context menu. I feel as though it may be related to 'tab' searching for nodes.

Natron version/commit (they can be retrieved from the About Window): 
Natron version 2.1.4 Release.
This software was compiled on Sep 20 2016 from the source code branch tags/2.1.4 at version f74f4c9 using GNU C++ version 5.3.0 with OpenMP 201307 targetting Intel x86-64 for Unix Environment.
The bundled openfx-io plugins were compiled from version 9ebe780.
The bundled openfx-misc plugins were compiled from version e9f080d.
The bundled openfx-arena plugins were compiled from version f4773da.

OS version: Windows 8 64-bit

**Comment by bebinalpha** [comment] 2016-10-18 10:57
any update on this bug guys

**Comment by olear** [comment] 2016-10-18 11:16
We are still unable to reproduce this issue.

**Comment by troywilliams1** [comment] 2016-10-25 16:57
This is the crash dump I generated from this, maybe it will help?

![crashread](https://cloud.githubusercontent.com/assets/18218357/19695795/2d1f8c90-9aaa-11e6-8dfb-ba016b365543.png)

**Comment by olear** [comment] 2016-10-25 17:01
@troywilliams1 Thanks for the report, but currently we are not able to get anything useful out of it since the report says the crash is in Qt4, and we don't have debug information for that library. We will have debug information for Qt4 soon, and you will then be able to send us better crash reports.

**Comment by olear** [comment] 2016-10-26 14:03
@troywilliams1 , @bebinalpha : Please download snapshot "2016-10-26 15:42:00 RB-2.1" and send us a new crash report.

**Comment by troywilliams1** [comment] 2016-10-26 19:56
#1473

**Comment by olear** [comment] 2016-10-26 21:11
Thanks, we are able to replicate the issue and will try to fix it as soon as possible.

> Press Tab key in node layout , type in 'read' and hit 'enter' key

We are only able to replicate this if we click 'read' with the mouse, not keyboard. Workaround for now is to use read from the menu or just press 'r'.

**Comment by troywilliams1** [comment] 2016-10-26 21:16
Just a heads up I dont think this is just read node specific, I noticed that if I use the tab key to generate several nodes (If I recall correctly, namely the Write node as well), that they all seem to come with some hiccups or problems. I can attempt to thumb through them all and see what sort of issues I can muster up. But I imagine if you give it a quick go you might notice some things offhand.

**Comment by olear** [comment] 2016-10-27 13:41
Fixed in 2.1.7 (and latest snapshot).

**Closed by olear** 2016-10-27 13:41 UTC
Labels: bug, gui
