### ISSUE TITLE
Reformats/Constants size result doesn't work reliably

### ISSUE THREAD

**Issue by CameraRick** [MrKepzie/Natron#1578] opened 2017-02-11 23:09 UTC
Building a PyPlug I experienced a weird issue with the Reformat and its result, the same with a Constant of a given size, it's a bit hard to describe so I give out the screenrecording right away: https://youtu.be/lghxu46QXUw

### Problem

The result of the Reformat/size of a Constant doesn't seem to give out the desired format or behaves strangely, at least with the pictured UI elements. Items that get merged on top that are outside of the projects format are not reliably appearing as they should; sometimes appearing in certain frames, but not others.

**Expected behavior:** the new format should override the project format completely and image anything that gets placed within it

**Actual behavior:** It doesn't work reliably

### Steps to Reproduce

1. create a constant with a large format (type set to "box") and / or a Reformat with said format
2. use a 2nd clip and transform it outside of the project format (e.g. HD) but within the given format from above
3. merge on top

### Versions

* **Natron version/commit:** Natron 2.2.4 stable
* **OS version:**  Windows 10 Pro

**Comment by MrKepzie** [comment] 2017-02-13 08:45
Could you send me this project privately, without the images, so I can reproduce it ?

**Comment by CameraRick** [comment] 2017-02-13 08:53
It's not as secret that I would need to send it in private :)
https://lucloud.fuke.it/index.php/s/75nIY1OeO7eWT88

I'm at work but that script is in my cloud, so the images will simply not be linked, I hope this works out? Else I could prepare it in 10hrs or so

**Comment by devernay** [comment] 2017-02-13 08:54
- when you want to have everything displayed, even what's outside of the project extent, press shift-C in the viewer to disable clipping - it gives you a better understanding of what happens
- the Reformat node maps the upstream format (HD) to your format (3572x5952), so that's why it elongates the Constant in the y directoction when you select Distort
- we don't set the format in generators when the extent is set to "size" because the size may be animated
- if you want to set the format without actually modifying the image, use NoOp

Does that make things more clear, and with this info are you able to do what you want?

**Comment by devernay** [comment] 2017-02-13 08:54
I am fixing the generators so that they set the output format, and their size can not be animated

**Comment by CameraRick** [comment] 2017-02-13 09:23
Hi there,

allow me to have a look at this when I get back home! :)
I don't know if I clearly got how to resolve this issue, a NoOp has no options so how do I set the format with it?
The info on the Generators makes sense, but I guess it would be great to have an option to actually set it as format? I mean in my case it's animated too, because I want to keep it dynamic, but still

I still don't get why it elongates the image that much though. Distort should "squeeze" x and y into position so it should just cap at the given format, no?

**Comment by devernay** [comment] 2017-02-13 09:33
let's say:
source RoD = 1920x5400
source format = 1920x1080
output format = 1920x5400
=>
computed transform with Resize Type = Distort (maps src format to dst format): x <- x; y <- 5*y
destination RoD = 1920x27000

NoOp has lots of options! Don't confuse it with Nuke's NoOp which does nothing.

**Comment by devernay** [comment] 2017-02-13 11:46
Lucas, there's now a "reformat" checkbox when Extent=Size on all generators. Please tell me if that solves the problem for you. It will be in the next snapshot (available within a few hours)

**Comment by CameraRick** [comment] 2017-02-13 19:54
Hi there,

I wasn't able to load a new snapshot, the list is empty for me, but I tried the approach with the NoOp.

So basically I got rid of the Reformat after the Constant and just used a NoOp as suggested; setting the 
format here did work well, thanks for that tip :)
Now the issue persists somehow. But I don't know if it's the same issue. What I encounter is that I still don't see the image in certain frames. Mostly it's black, on some frame it's there again, as you can see in the demo-video I took too. So may this be a different issue?

Regarding the Reformat and the distort: I'm not smart enough to get the math behind it, but I don't see what it gets multiplied. I mean, it should just set a format, no? That's what I at least think of a reformat set to "box", that it just outputs what I type there, regardless of the scaling-type?

**Comment by devernay** [comment] 2017-02-15 15:08
Reformat resizes the image and sets the format. NoOp just sets the format (it's a metadata) and doesn't modify the image

**Comment by CameraRick** [comment] 2017-02-15 18:48
Yes I got that, just asking myself why the Reformat behaves as it does, because it's surely not expected :o

Anyways, the issue somehow persists. I still can't see any snapshots on the site (the list is empty, tried two browsers and two machines).
I still can't reliably merge things as in the video example though, on some frames they appear, on some not. Maybe I have to use a NoOp to set the format before the initial transform that places the image outside the RoI? I think that could mess with the expressions easily :/

**Comment by devernay** [comment] 2017-02-16 16:45
Snapshots are coming, closing. Reopen if issue persists after next snapshot/release

**Comment by CameraRick** [comment] 2018-03-30 22:52
I don't know if it's exacly the same bug, but it happens when I'm at the same project as a year ago. I can hardly describe it so here's a video to show what the issue is: https://youtu.be/pdsw0wc-o7s

**Comment by devernay** [comment] 2018-03-31 05:52
The bug seems to be that Merge(over) is passthrough for no obvious reason

**Comment by devernay** [comment] 2018-03-31 08:54
Should be fixed, you may test in the next snapshot

**Comment by devernay** [comment] 2018-03-31 08:55
@CameraRick please close this issue if it's fixed

**Comment by CameraRick** [comment] 2018-03-31 22:15
It works now :) I noticed another bug, but I will make a new issue for that. THANK YOU very much!

**Closed** 2018-03-31 22:15 UTC
Labels: func:plugins, info:feedback-needed, prio:normal, status:confirmed, type:feature, ver:2.x
