### ISSUE TITLE
scrolling in the nodegraph while dragging a node ?

### ISSUE THREAD

**Issue by mathiastesar** [MrKepzie/Natron#986] opened 2015-10-29 17:45 UTC
Is it possible to scroll in the nodegraph view while dragging a node ?. It s quite an important feature even if it looks basic. thanks team !

**Comment by MrKepzie** [comment] 2015-10-29 17:50
Duplicate of https://github.com/MrKepzie/Natron/issues/766

**Closed by MrKepzie** 2015-10-29 17:50 UTC
