### ISSUE TITLE
Alpha of "B" Sometimes Unchecks

### ISSUE THREAD

**Issue by ElDirector** [MrKepzie/Natron#1482] opened 2016-11-10 03:35 UTC
### Problem

Sometimes when adding nodes below a Merge node, a Merge in the upline will disable the alpha of the B pipe.  

**Expected behavior:** 
I expect the Merge to remain where I set it.

**Actual behavior:** 
The alpha checkbox for B is unchecking itself randomly.  
The result is that the image in the viewer is negativly affected, often appearing washed out or clipped due to the alpha being missing from the merge.  Depending on the size of the project, it can take a few minutes to find which Merge(s) is/are the culprits.  

Here's a link to a script I saved when it happened.
http://s000.tinyupload.com/index.php?file_id=55021116185528423329

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

You may submit a link to any screenshots/videos that can be used to understand how to reproduce the issue.

### Versions

* **Natron version/commit** (they can be retrieved from the About Window): 2.1.7
* **OS version:** 
Windows 10 Anniversary

**Comment by MrKepzie** [comment] 2016-11-10 08:43
It happens when you connect in the B input something that is RGB instead.
The reason why is because if A is RGBA and B is RGB, then if the Merge node will convert (actually Natron) the B RGB input to RGBA using alpha = 1. 
In that case, imagine the A input has its alpha channel with the result of a keying operation, then applying the _over_ operator on the B image (which has its alpha to 1 everywhere) would produce a resulting alpha channel full of 1 everywhere, whereas the user would expect to see the result of the alpha in the A input instead.

There was indeed a small bug where the B alpha checkbox would automatically uncheck/check even if you uncheck it yourself. This has been fixed and will no longer automatically toggle if you changed it yourself.


We will add documentation for these scenarios.

**Comment by ElDirector** [comment] 2016-11-11 19:03
Thanks.  The bug is fixed in the nightly builds I assume?  I was running 2.1.7

**Comment by ElDirector** [comment] 2016-11-15 18:06
Just had this "B alpha uncheck" in the merge happen again in the nightly I'm running.

**Comment by devernay** [comment] 2017-12-11 18:39
Reopening. Can you please re-upload a sample script? You can attach zip files to github issues.

**Comment by ElDirector** [comment] 2017-12-11 18:53
[Merge Issue.ntp.zip](https://github.com/MrKepzie/Natron/files/1549002/Merge.Issue.ntp.zip)

**Comment by devernay** [comment] 2017-12-11 19:51
see https://www.facebook.com/groups/NatronNation/permalink/904970263003876/

**Comment by devernay** [comment] 2017-12-11 21:48
duplicate of https://github.com/MrKepzie/Natron/issues/1704
closing

**Closed by devernay** 2017-12-11 21:48 UTC
