### ISSUE TITLE
Network access and Reformat.

### ISSUE THREAD

**Issue by kirang4e** [MrKepzie/Natron#409] opened 2015-01-19 19:22 UTC
( I have created this thread fewdaysback 
https://github.com/MrKepzie/Natron/issues/381
I'm really sorry for the late reply.I was out of station,so could not reply back. Pardone me. )

I will address my issues one by one.
Reformat:
I want to reformat only one element in my comp. say for example,a BG matte paint which is of size 5K.Need to reformat it to 2048x872. in nuke's reformat we can create new format.
![reformat](https://cloud.githubusercontent.com/assets/10396656/5798545/3acc1600-9fee-11e4-9faf-1e3812a78a36.png)
 but in ResizeOIIO,I can not find it.It can import .nps format. so how can I define my own resolutions and import them in ResizeOIIO??

 Network Access:
Usually I access my footage from network.. I can directly paste server path in nuke's node graph.I tried same in Natron.its not working,not even in read dailogue box.. My server path is something like "//server1/proj/scene/shot1/scan/0001.exr" how to browse them?,without mapping network drives in local?.

Exporting to other platforms:
(May be this question is little weird)
Can we export roto nodes from Natron to Nuke? in future versions? 

My questions are mostly refering to nuke,I don't want to compate Natron V 1.0 to Nuke.It is still in develoment stage.but I'm just little curious :D 
I have posted these queries in facebook group and following.

**Comment by sozap** [comment] 2015-01-19 23:00
I think I've read in one forum post that it's impossible to set custom format in ResizeOIIO because of an OpenFX limitation...
And about exporting Roto from Natron to Nuke, I guess that should be doable with a python script ...
Once the python API will be released we should see many little improvements of that kind, as it's easier to do scripting than C++ coding...
Alex will correct me if I'm wrong.

Cheers !

**Comment by MrKepzie** [comment] 2015-01-20 17:21
Hello, 

Yes @sozap  is correct.
However I think you forgot the "type" parameter which lets you choose a custom size and pixel aspect ratio.

Exporting a roto node to Nuke is the perfect role of a Python script. I'll let the community do its job on that... 

Regarding the server access, if I understand correctly you don't want to use a p:/ prefix but a server name ? I'd have to debug it on windows

**Comment by kirang4e** [comment] 2015-01-20 18:06
Hello,
Yes,I have checked size and scale too.. say for example I have a
2K_super_35 scan (2048X1556) but need to  deliver 2048X872 as output.  we
are missing resize type..Widht,height,fit,fill..etc.We can achieve them
with combination of resizeOIIO/transform/crop.but applying more filters may
affect the quality.Need to do it all time manually,can't save it as preset
or custom format. Hope we will get an all in one reformat node. :)

Regarding the server,yes that is what I need.Need to access without any
drive letter.

On Tue, Jan 20, 2015 at 10:51 PM, Alexandre Gauthier <
notifications@github.com> wrote:

> Hello,
>
> Yes @sozap <https://github.com/sozap> is correct.
> However I think you forgot the "type" parameter which lets you choose a
> custom size and pixel aspect ratio.
>
> Exporting a roto node to Nuke is the perfect role of a Python script. I'll
> let the community do its job on that...
>
> Regarding the server access, if I understand correctly you don't want to
> use a p:/ prefix but a server name ? I'd have to debug it on windows
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/MrKepzie/Natron/issues/409#issuecomment-70693938>.
>



--

**Comment by adallafontana** [comment] 2015-01-21 07:22
>Need to do it all time manually,can't save it as preset or custom format.

If this can help at this moment you can save a preset like "external preset", after just load in other comp.

**Comment by kirang4e** [comment] 2015-01-22 03:44
Ok.Thank you :)
I'm eagerly waiting for network access.We have many servers,If I map only 5
data servers..other artist may use 8 other servers,so drive letters will be
different and he can't use my file.While working in Natron,I need to copy
data to local machine.Hope we can get it in next version.

On Wed, Jan 21, 2015 at 12:52 PM, Alessandro Dalla Fontana <
notifications@github.com> wrote:

> Need to do it all time manually,can't save it as preset or custom format.
>
> If this can help at this moment you can save a preset like "external
> preset", after just load in other comp.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/MrKepzie/Natron/issues/409#issuecomment-70794913>.
>



--

**Comment by kirang4e** [comment] 2015-01-22 06:21
![resize](https://cloud.githubusercontent.com/assets/10396656/5851355/03d841b0-a22c-11e4-9b6f-7666501f06ff.png)
Now 2 filters have applied.Can't avoid them.

Can I post my other issues in this thread itself? or should I open new threads??

**Comment by MrKepzie** [comment] 2015-01-22 07:58
The network issue will be fixed for the next version.

Please open a separate thread for another issue so that we know what's left to do without digging into all the posts.

I do not understand what's wrong on your screenshot

**Comment by kirang4e** [comment] 2015-01-22 08:43
ok sorry.That screenshot referring to Reformat node.
We don't have alignment type in ResizeOIIO. Need to add transform or crop nodes to solve it.But if we add more nodes,more filters will apply and they may reduce quality. Will ResizeOIIO and transfrom/crop nodes concatenate ?? 
( http://www.nukepedia.com/written-tutorials/concatenation-of-transforms-in-nuke/ )

**Comment by Aledante** [comment] 2015-01-22 15:26
Hi,

This is my first post, and my english is not so good. I have the same problem: 1.1.0 and 1.0 crash when opening filebrowser... bug #413 . And I was reading 409 and 404, but i didn´t find what to do to fix it.

I want to tell you that de software seems to be great and i really apreciate the work!

Thanks!

**Comment by MrKepzie** [comment] 2015-01-24 10:53
Resize do not concatenate as it does not use a matrix transformation. 
Crop does not apply a transform matrix in any way so it won't concatenate.

Regarding the file browser crash, I cannot reproduce it on Windows 7 even with a Network drive, so I guess the issue is elsewhere, probably Windows 8 related. A video of the crash would help.

**Comment by devernay** [comment] 2015-07-22 14:36
Is this still an issue, or can we close it?

**Comment by MrKepzie** [comment] 2015-07-22 14:38
The network crashes are fixed, though the formats list enhancement is not implemented

**Closed** 2016-01-27 08:45 UTC
Labels: enhancement
